
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serverUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  main:
    web-application-type: reactive
  application:
    name: APIGateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: authentication-service
          uri: http://localhost:8088/
          predicates:
            - Path=/userauth/**
          filters:
            - RewritePath=/userauth(?<segment>/?.*), $\{segment}



        - id: menu-service
          uri: http://localhost:8085/
          predicates:
            - Path=/menuuser/**
          filters:
            - RewritePath=/menuuser(?<segment>/?.*), $\{segment}



        - id: user-service
          uri: http://localhost:8086/
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user(?<segment>/?.*), $\{segment}



        - id: recommendation-service
          uri: http://localhost:8282/
          predicates:
            - Path=/userrecommendation/**
          filters:
            - RewritePath=/userrecommendation(?<segment>/?.*), $\{segment}


        - id: order-service
          uri: http://localhost:8083/
          predicates:
            - Path=/orderservice/**
          filters:
            - RewritePath=/orderservice(?<segment>/?.*), $\{segment}


        - id: payment-service
          uri: http://localhost:9090/
          predicates:
            - Path=/paymentservice/**
          filters:
            - RewritePath=/paymentservice(?<segment>/?.*), $\{segment}


        - id: notification-service
          uri: http://localhost:9191/
          predicates:
            - Path=/usernotification/**
          filters:
            - RewritePath=/usernotification(?<segment>/?.*), $\{segment}


        - id: product-webapp
          uri: http://localhost:4200/
          predicates:
            - Path=/**
          filters:
            - RewritePath=(?<segment>/?.*), $\{segment}